collections:
  projectsInfoIT:
    output: true
    permalink: /it/projects/:name/
  projectsInfoEN:
    output: true
    permalink: /en/projects/:name/
  extraInfoIT:
    output: true
    permalink: /it/extra/:name/
  extraInfoEN:
    output: true
    permalink: /en/extra/:name/
