name: Aggiorna Graduatorie

on:
  schedule:
  - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  aggiorna_graduatorie:
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install bash curl git python3 python3-pip
        sudo pip3 install beautifulsoup4
    - name: Pull repository
      uses: actions/checkout@v2
    - name: Get GraduatorieScript
      run: curl -Lo aggiorna_graduatorie.py https://raw.githubusercontent.com/PoliNetwork/GraduatorieScript/main/main.py
    - name: Run aggiorna_graduatorie.py
      run: python3 ./aggiorna_graduatorie.py "$(git rev-parse --show-toplevel)/graduatorie"
    - name: Create commit
      run: |
        [[ -z $(git status --porcelain) ]] && exit 0
        git add .
        git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git config --local user.name 'github-actions[bot]'
        TZ= printf -v commit_msg 'update graduatorie: %(%c)T'
        git commit -m "$commit_msg"
    - name: Push commit to master
      uses: ad-m/github-push-action@master
      with:
        branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}
